[workspace]
members = [
    "ckb-debugger",
    "ckb-debugger-api",
    "ckb-mock-tx-types",
    "ckb-vm-debug-utils",
    "ckb-vm-pprof",
    "ckb-vm-pprof-converter",
    "ckb-vm-signal-profiler"
]
