[package]
name = "ckb-vm-pprof"
version = "0.109.0"
authors = ["mohanson <mohanson@outlook.com>"]
edition = "2021"

[dependencies]
addr2line = "0.13.0"
clap = "2.33"
ckb-vm = { version = "=0.24.0-beta", features=["pprof"] }
goblin = "0.4"
object = "0.20"
